  name: Grype Security Scan

  on:
    workflow_dispatch:
      inputs:
        repo_url:
          description: 'Repository URL to scan'
          required: true
        branch:
          description: 'Branch to scan'
          required: true
          default: 'main'
        callback_url:
          description: 'Callback URL for results'
          required: true
        scan_id:
          description: 'Scan ID for tracking'
          required: true

  jobs:
    scan:
      runs-on: ubuntu-latest
      steps:
        - name: Extract repo info
          id: repo_info
          run: |
            REPO_URL="${{ github.event.inputs.repo_url }}"
            # Remove https://github.com/ prefix if present
            REPO_PATH=$(echo $REPO_URL | sed 's|https://github.com/||' | sed 's|.git$||')
            echo "repo_path=$REPO_PATH" >> $GITHUB_OUTPUT

        - name: Checkout target repository
          uses: actions/checkout@v4
          with:
            repository: ${{ steps.repo_info.outputs.repo_path }}
            ref: ${{ github.event.inputs.branch }}

        - name: Run Grype scan
          id: grype
          uses: anchore/scan-action@v3
          with:
            path: "."
            fail-build: false
            output-format: json

        - name: Prepare results
          id: prepare
          run: |
            # Add scan metadata to results
            RESULTS=$(cat ${{ steps.grype.outputs.json }})
            ENHANCED_RESULTS=$(jq --arg scan_id "${{ github.event.inputs.scan_id }}" \
              --arg repo "${{ github.event.inputs.repo_url }}" \
              --arg branch "${{ github.event.inputs.branch }}" \
              '. + {scan_id: $scan_id, repository: $repo, branch: $branch, timestamp: now | todate}' \
              <<< "$RESULTS")
            echo "$ENHANCED_RESULTS" > results.json

        - name: Send results to callback
          run: |
            curl -X POST "${{ github.event.inputs.callback_url }}" \
              -H "Content-Type: application/json" \
              -H "X-Scan-ID: ${{ github.event.inputs.scan_id }}" \
              --data-binary @results.json \
              --max-time 30 \
              --retry 3 \
              --retry-delay 5
