  name: Grype Security Scan

  on:
    workflow_dispatch:
      inputs:
        repo_url:
          description: 'Repository to scan (format: owner/repo)'
          required: true
        branch:
          description: 'Branch to scan'
          required: true
          default: 'main'
        scan_id:
          description: 'Scan ID for tracking'
          required: true
        callback_url:
          description: 'Callback URL for results'
          required: true

  jobs:
    scan:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout target repository
          uses: actions/checkout@v4
          with:
            repository: ${{ github.event.inputs.repo_url }}
            ref: ${{ github.event.inputs.branch }}

        - name: Run Grype scan
          id: grype
          run: |
            # Install Grype
            curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

            # Run scan and save JSON output
            grype dir:. -o json > grype-results.json

            # Add metadata to results
            cat grype-results.json | jq \
              --arg scan_id "${{ github.event.inputs.scan_id }}" \
              --arg repo "${{ github.event.inputs.repo_url }}" \
              --arg branch "${{ github.event.inputs.branch }}" \
              --arg timestamp "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
              '. + {scan_id: $scan_id, repository: $repo, branch: $branch, timestamp: $timestamp}' \
              > enriched-results.json

        - name: Send results to callback
          if: always()
          run: |
            echo "Sending results to callback URL..."
            curl -X POST "${{ github.event.inputs.callback_url }}" \
              -H "Content-Type: application/json" \
              -H "X-Scan-ID: ${{ github.event.inputs.scan_id }}" \
              -d @enriched-results.json \
              --max-time 30 \
              --retry 3 \
              -v

            echo "Results sent successfully!"
